// <auto-generated />
using System;
using CCMovieDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CCMovieDatabase.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20251206034948_MovieSeedData")]
    partial class MovieSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CCMovieDatabase.Models.ActingCredit", b =>
                {
                    b.Property<int>("ActingCreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActingCreditId"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("ActingCreditId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("PersonId");

                    b.ToTable("ActingCredits");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            Author = "Jesse",
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            ModifiedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Lorem Ipsum and stuff",
                            Slug = "hello_world",
                            ThumbnailUrl = "https://craftypixels.com/placeholder-image/300",
                            Title = "Welcome to CCMovieDatabase"
                        },
                        new
                        {
                            ArticleId = 2,
                            Author = "Jesse",
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            ModifiedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Lorem Ipsum and stuff",
                            Slug = "hello_world2",
                            ThumbnailUrl = "https://craftypixels.com/placeholder-image/300",
                            Title = "More Movies Added"
                        },
                        new
                        {
                            ArticleId = 3,
                            Author = "Jesse",
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            ModifiedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Lorem Ipsum and stuff",
                            Slug = "hello_world3",
                            ThumbnailUrl = "https://craftypixels.com/placeholder-image/300",
                            Title = "For the love of movies"
                        },
                        new
                        {
                            ArticleId = 4,
                            Author = "Jesse",
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            CreatedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsFeatured = true,
                            ModifiedAt = new DateTime(2025, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "Lorem Ipsum and stuff",
                            Slug = "hello_world4",
                            ThumbnailUrl = "https://craftypixels.com/placeholder-image/300",
                            Title = "I wrote this"
                        });
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Computer Accessories"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Graphics Cards"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Monitors"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Hard Drives"
                        });
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Character", b =>
                {
                    b.Property<int>("CharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CharacterId");

                    b.HasIndex("MovieId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.CrewCredit", b =>
                {
                    b.Property<int>("CrewCreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrewCreditId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("CrewCreditId");

                    b.HasIndex("MovieId");

                    b.HasIndex("PersonId");

                    b.ToTable("CrewCredits");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ThumbnailURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mean lord exiles fairytale creatures to the swamp of a grumpy ogre, who must go on a quest and rescue a princess for the lord in order to get his land back.",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(2001, 4, 26),
                            ThumbnailURL = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTG_q0A0cypAsXxYlgs5J_554BrcnjeeKExlQE3ZaZUuPYv0fUd",
                            Title = "Shrek"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Shrek is back baby!",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(2002, 4, 26),
                            ThumbnailURL = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTPx7lW6h0G1O9-npEnVPL07fT74Tp6SFl0i47nxfypyVBcQFdS",
                            Title = "Shrek 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A world-class playboy and part-time secret agent from the 1960s emerges after thirty years in a cryogenic state to battle with his nemesis Dr. Evil.",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(1997, 5, 2),
                            ThumbnailURL = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTlO5X0VeATdsHkdAiSqrIjnibxUZFxHvr56dYDONVdRyNsdJyhhAgLl7cMeUZX_nJL1szd1r0PWHMyHtWNoVVvP1FZNLZ6-A",
                            Title = "Austin Powers: International Man of Mystery"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dr. Evil is back and has invented a new time machine that allows him to go back to the 1960s and steal Austin Powers' mojo, inadvertently leaving him \"shagless\".",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(1999, 6, 11),
                            ThumbnailURL = "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSIfeD5mGXpWtcfJ_ycbhE_9ZAqnEugZyaEOd9vnjZYPipvpQq2olg1Bl2uyE6N_VcV7L0cnGIGgg8WqQD-fRo-USv7_4lLeQ",
                            Title = "Austin Powers: The Spy Who Shagged Me"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Upon learning that his father has been kidnapped, Austin Powers must travel to 1975 and defeat the aptly named villain Goldmember, who is working with Dr. Evil.",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(2002, 7, 26),
                            ThumbnailURL = "https://static.qobuz.com/images/covers/66/49/0081227784966_600.jpg",
                            Title = "Austin Powers in Goldmember"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A troubled security guard begins working at Freddy Fazbear's Pizza. During his five nights on the job, he realizes that something is wrong with the pizzeria and pretty soon finds the truth about its animatronics.",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(2023, 10, 27),
                            ThumbnailURL = "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTaydvBSSHZ_qYRr2QlfuisPN1JxzqmasvFmmuhCn9-vLzw6D1cY7NXscySkTHC80g2ASZKzSi2ATEICdak16TVc_kxIkeXFA",
                            Title = "Five Nights at Freddy's"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Anyone can survive five nights. This time, there will be no second chances.",
                            RatingId = 1,
                            ReleaseDate = new DateOnly(2025, 12, 5),
                            ThumbnailURL = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQlGcWZganGfskXyYsVD1UMZmtaXp2y7nlxqJlWXAkAMSRYG6QgGZ-OCUAt77g7EC5Md-gD-7Ht8mV2OKFLj-nPQjUPW5a9DA",
                            Title = "Five Nights ar Freddy's 2"
                        });
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "A simple mass produced keyboard",
                            Name = "Dell Keyboard"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "A very expensive video card",
                            Name = "RTX 5090"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "An enterprise widescreen monitor",
                            Name = "Dell Widescreen Monitor"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "Western Digital Black Edition SSD",
                            Name = "WD Black Edition SSD"
                        });
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            RatingId = 1,
                            Name = "PG-13"
                        },
                        new
                        {
                            RatingId = 2,
                            Name = "R"
                        },
                        new
                        {
                            RatingId = 3,
                            Name = "G"
                        });
                });

            modelBuilder.Entity("CCMovieDatabase.Models.ActingCredit", b =>
                {
                    b.HasOne("CCMovieDatabase.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMovieDatabase.Models.Person", "Person")
                        .WithMany("ActingCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Character", b =>
                {
                    b.HasOne("CCMovieDatabase.Models.Movie", "Movie")
                        .WithMany("Characters")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.CrewCredit", b =>
                {
                    b.HasOne("CCMovieDatabase.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CCMovieDatabase.Models.Person", "Person")
                        .WithMany("CrewCredits")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Movie", b =>
                {
                    b.HasOne("CCMovieDatabase.Models.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Product", b =>
                {
                    b.HasOne("CCMovieDatabase.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Movie", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("CCMovieDatabase.Models.Person", b =>
                {
                    b.Navigation("ActingCredits");

                    b.Navigation("CrewCredits");
                });
#pragma warning restore 612, 618
        }
    }
}
